### Site metadata ###

name: Junaid Farooq
title: Junaid Farooq
description: Ruby, Elixir, DevOps
meta_description: "Ruby, Elixir, DevOps"

### Build settings ###

url: "https://ijunaidfarooq.com"
baseurl: ""

permalink: /:year/:title/

aboutPage: true

github:
  - metadata

plugins:
  - jekyll-paginate
  
paginate: 20

# Reminder that empty string matches all files.
defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
  - scope:
      path: "" 
      type: pages
    values:
      layout: default
